name: Release Go-Gather

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Checks"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install semantic-release@25.0.3 @semantic-release/github@12.0.6 @semantic-release/commit-analyzer@13.0.1 @semantic-release/release-notes-generator@14.1.0 conventional-changelog-conventionalcommits@9.3.0

      - name: Tag release if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Running Semantic Release"
            npx semantic-release
